package daikon.hdfs;
import daikon.*;
import java.util.Set;
import java.util.ArrayList;
import java.util.List;
//this class is automatically generated by our scripts
public class InvariantPool{

	public static List<Invariant> invariants = new ArrayList<>();

	static {
		invariants.addAll(InvariantPool999.invariants999);
		invariants.addAll(InvariantPool1999.invariants1999);
		invariants.addAll(InvariantPool2999.invariants2999);
		invariants.addAll(InvariantPool3999.invariants3999);
		invariants.addAll(InvariantPool4999.invariants4999);
		invariants.addAll(InvariantPool5999.invariants5999);
		invariants.addAll(InvariantPool6999.invariants6999);
		invariants.addAll(InvariantPool7999.invariants7999);
		invariants.addAll(InvariantPool8507.invariants8507);
	}
}
