package daikon.zookeeper;
import daikon.*;
import java.util.Set;
import java.util.ArrayList;
import java.util.List;
//this class is automatically generated by our scripts
public class InvariantPool{

	public static List<Invariant> invariants = new ArrayList<>();

	static {
		invariants.addAll(InvariantPool999.invariants999);
		invariants.addAll(InvariantPool1999.invariants1999);
		invariants.addAll(InvariantPool2999.invariants2999);
		invariants.addAll(InvariantPool3999.invariants3999);
		invariants.addAll(InvariantPool4999.invariants4999);
		invariants.addAll(InvariantPool5999.invariants5999);
		invariants.addAll(InvariantPool6999.invariants6999);
		invariants.addAll(InvariantPool7999.invariants7999);
		invariants.addAll(InvariantPool8999.invariants8999);
		invariants.addAll(InvariantPool9999.invariants9999);
		invariants.addAll(InvariantPool10999.invariants10999);
		invariants.addAll(InvariantPool11999.invariants11999);
		invariants.addAll(InvariantPool12999.invariants12999);
		invariants.addAll(InvariantPool13412.invariants13412);
	}
}
