package daikon.cassandra;
import daikon.*;
import java.util.Set;
import java.util.ArrayList;
import java.util.List;
//this class is automatically generated by our scripts
public class InvariantPool{

	public static List<Invariant> invariants = new ArrayList<>();

	static {
		invariants.addAll(InvariantPool999.invariants999);
		invariants.addAll(InvariantPool1999.invariants1999);
		invariants.addAll(InvariantPool2796.invariants2796);
	}
}
